apiVersion: apps/v1
kind: Deployment
metadata:
  name: safebank-deployment
  labels:
    app: safebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: safebank
  template:
    metadata:
      labels:
        app: safebank
    spec:
      containers:
      - name: safebank-container
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: safebank-html
