apiVersion: v1
kind: Pod
metadata:
  name: safebank-pod
  labels:
    app: safebank
spec:
  containers:
  - name: safebank-container
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    configMap:
      name: safebank-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: safebank-html
data:
  index.html: |
    <html>
      <head><title>SafeBank Digital</title></head>
      <body>
        <h1>SafeBank - Aplicação Kubernetes</h1>
      </body>
    </html>
